<?php
$trad['home'] = "Home";
$trad['historia'] = "History of Games";
$trad['plataformas'] = "Current Platforms";
$trad['jogos'] = "Game of the Year";
$trad['mapa'] = "Site map";

/*pagina historia dos games*/

$trad['magnavox'] ="Magnavox Odssey - 1972";
$trad['tmagnavox'] = "The Magnavox Odssey was the first video game console for indoor television connection. It was created by Ralph Baer who finished the prototype in 1968. Arrives in the United States in 1972 the first video game console, the Odyssey 100, manufactured by Magnavox, a subsidiary of Dutch Philips. There were 12 games for the console, which could be exchanged by the user for a more rudimentary mechanism than the cartridges. Despite its simplicity, the equipment offered an optional rifle for shooting games. Interesting trivia about the Odyssey 100 is the need to note down the points of the games they had (and therefore paper sheets accompanied the game) and that users had to place cards in front of the TV screen to simulate the field of play a tennis game for example, a green card was placed to look like grass).";

$trad['pong'] = "Atari Pong - 1975";
$trad['tpong'] = "Pong the Atari console arrived in 1975. Created by engineer Harold Lee, it was a simple Ping Pong game with two vertical bars and a ball (square), without speed control or reflection. He started a series of video games with this design of two motion control buttons. It sold 150,000 units in a year, an expressive brand for the time. Pong, the arcade game created by Bushnell at Atari, becomes a phenomenon and several companies, such as Ramtek and Nutting, start to launch similar ones. Atari establishes contact with Japan's Namco.";

$trad['coleco'] = "Coleco Telstar - 1976";
$trad['tcoleco'] = "The Telstar series is a series of Pong machines launched by Coleco. With this videogame, Coleco led the first generation of video games. The console was very successful because of its low prices (cost $ 50 on average) and a bit of luck. Coleco reached first place in the sale of first generation consoles thanks to low prices and extra luck. At that time there were many companies wanting to get into the video game business, the only problem being that there were few chip makers. The leading manufacturer of the time was General Instruments, which was overloaded service, however, Coleco went ahead in the orders of his chip was the only one to receive all the order at once.";
$trad['tcoleco2'] = "With the overburdening of chip-producing companies, some of Coleco's large competitors received only 20% of the order. Result: Coleco led. The Telstar console below was released in 1976 and had only 3 games with 3 difficulty levels. In all simplicity, more than one million units were sold worldwide.";

$trad['2600'] = "Atari 2600 - 1977";
$trad['t2600'] = "Atari 2600 was a video game designed by Nolan Bushnell and released in 1978 in the United States and in 1983 in Brazil. Considered a cultural symbol of the 1980s, it was a sales phenomenon in Brazil between the years 1984 to 1986 and its games remain in the memory of many who lived the youth at this time.";

$trad['telejogo'] = "TeleJogo - 1979/1980";
$trad['ttelejogo'] = "Telejogo was a simple video game machine produced in Brazil by philco. It consisted basically of traits that went up or down to rebound a square, the control was done through a dial (like the radio tuner). In Brazil it was marketed in 1977 by Ford and Philco. The second console in addition to the 10 games of that version (Hockey, Tennis, Wall I, Wall II, Basketball I, Basketball II, Football, Barrier, Target Shooting I, Target Shooting II) had another detail that stood out, the joysticks. With them, it was no longer necessary to be close to the console to play (quite different from the first model). But once the Philco / Ford fitted the finish, using light wood, giving an elegant touch to the device. Another interesting point of the design is that the TeleJogo II (as well as the TeleJogo) is not simply a copy of some foreign Pong, but a totally Brazilian project, showing that the national manufacturers had total capacity to compete with imported devices ";

$trad['intellivision'] = "Intellivision I - 1980";
$trad['tintellivision'] = "Intellivision I was the first console created by Mattel in 1980. At the time of its launch, it cost $ 300. In all, 125 games were released for the console between the years 1979 and 1989. The console stayed on the market even after the great Crash of 1984, where the US video game market suffered its biggest drop and all video games lost value and credibility. The first version was available until 1983. Intellivision Keyboard Component - Transforms Intellivision into a computer. The keyboard had the Motorola 6502 (8 bits) as the microprocessor and worked in conjunction with the console hardware.";
$trad['tintellivision2'] = "<br/>It also had 16Kb of RAM (expandable up to 8 Mb), digitally controlled cassette recorder for recording / reading data and audio reading, expansion ports and printer input. PlayCable - Launched in 1981, the accessory let you play via cable. The subscriber lowered the game to the console. Just like the keyboard, it was plugged into the input of the cartridge. It was discontinued in 1983. Intellivoice - Launched in 1982, this accessory added voices to the video game. He had a speech synthesizer chip. Only 13 games were compatible with him. Its manufacture finished on August 4, 1983.";

$trad['nes'] = "Nintendo (NES) - 1985";
$trad['tnes'] = "Nintendo Entertainment System, or simply NES (in Brazil nicknamed Nintendinho), is a videogame released by Nintendo in North America, Europe, Asia, Australia and Brazil. Originally released in Japan in 1983 under the name of Nintendo Family Computer, or just Famicom, the system was redesigned and received the new name to be released on the American market in 1985. The NES / Famicom was the most commercially successful video game in its time , helped the video game industry recover from the 1983 crisis and set new standards that would be followed by the industry. It was also the first console to be produced by third parties, which helped spread the system around the world. The NES was also one of the first consoles to rely on games made by third parties (not only by the manufacturer itself). Your model code is NES-001 ..";

$trad['7800'] = "Atari 7800 - 1986";
$trad['t7800'] = "Atari 7800 is a video game console released by Atari in June 1986. It was developed to replace the Atari 5200, which was a market failure, and re-establish Atari's supremacy over Intellivision and The Atari 7800 is designed to meet the recent rivals of the failed Atari 5200, The Nintendo Entertainment System (NES) and the Sega Master System with a processor working at a faster speed than rivals, and with a processor of audio of two separate channels, the Atari 7800 had a superior performance in speed to the NES and graphics and sounds of similar quality to the Sega Master System. However, what decreed the failure of the Atari 7800, even being superior to the competitor, was the low game collection , since most of the successful Software House of the time, such as: Taito, Namco, Capcom and Activision itself, responsible for Atari's biggest hits in the Atari 2600 era, with Nintendo. ";
    
$trad['3d0'] = "3DO Interactive Multiplayer - 1993";
$trad['t3d0'] = "3DO Interactive Multiplayer (commonly called 3DO) was the first home video game with 32-bit architecture. The 3DO consists of technical specifications created by the (3DO Company), which is a partnership between 7 different companies. These specifications are intellectual property of the (3DO Company) and are the main part for anyone who wants to develop a console compatible with 3DO Interactive Multiplayer. The manufacturing companies licensed the copyright of 3DO to manufacture a system based on the specifications of the 3DO Company, and software companies licensed the right to develop software (games and programs) for 3DO systems.";

$trad['jaguar'] = "Jaguar - 1993";
$trad['tjaguar'] = "Jaguar was a video game released by Atari in the early 1990s to compete with the 16-bit consoles of Sega and Nintendo. The Jaguar had five processors, 68000 family, four for general processing and one for sound. The original project began in the late 1980s, under the name of Phanter. It was a powerful system for the time, with 16-bit processor and better graphic resolution than the Super Nintendo. But new 32-bit video games were released as the Amiga CD-32 and 3DO, Atari decided to improve the processing and launch a pseudo 64-bit. The new media for games was the CD, Jaguar was the only one of the new ones that still used the already outdated cartridges. With little support from outsourced companies, and an eminent failure in view of the new SEGA Sega Saturn and Sony Playstation consoles, Atari decided to launch an external CD drive, thus renaming the Jaguar CD";
$trad['tjaguar2'] = "<br />Few Jaguar-CD's and drives for this console have been sold. Fewer still were the games made for the Jaguar-CD. Considered a failure, the Jaguar-CD came to an end with Atari's bankruptcy in 1996.";

$trad['snk'] = "Snk Neo-Geo CD - 1994";
$trad['tsnk'] = "Due to the high price of the Neo-Geo AES, SNK decided to launch a cheaper model, since the cartridge console was extremely expensive, and its games also (a good game cost about $ 300, the launch price of Neo-Geo CD), the solution was to use the CD instead of the cartridge. It was born the Neo-Geo CD, which owed nothing to the original Neo-Geo, and had an improved sound due to the cd system, its games were also much cheaper, due to the use of the cd, which cost on average 5 times less than the cartridges used in Neo-Geo, the console also read music CDs. The first released version was the Neo-Geo CD drawer, which came out only in the Japanese market, nowadays it is a console quite difficult to find.";
$trad['tsnk2'] = "Soon after, the Neo-Geo CD cover model was released worldwide, where the cd was put on the top of the console, this is the most common and easy to find model. After all, the Neo-Geo CD had a serious problem, due to its 1X speed cd drive, the games were loaded very slowly, which made the gameplay a task of patience sometimes, to try to solve this, the SNK released the NeoGeo CDZ which carried the games faster (some say that the CD drive was 2x, and some say the CD drive was the same but the console had more memory, which carried the most games Neo-Geo was already in decline, due to the high price of the cartridge versions, and the slowness of the cd version, which made Neo-Geo a commercial failure, however, its list of games were great, with perfect arcade conversions. Neo-Geo has a lot of fans to this day. ";

$trad['saturn'] = "Sega Saturn - 1995";
$trad['tsaturn'] = "Sega Saturn is a 32-bit video game launched by Sega in 1994, Japan and 1995 in the US (and Brazil through Tec Toy). The development of the Sega Saturn was composed of a lot of speculation, since it was not the custom of the companies to divulge much concrete information during the development of their products. In the middle of 1991 several news appeared on a new console in development by Sega called GigaDrive, that would be based on the new Plate System 32 that was beginning to be used in the arcades of the time. Just as the Genesis originated from System 16 board, it made sense to believe that the GigaDrive was being developed using the System 32 as a base. But time passed and never was an official confirmation on the GigaDrive from Sega . ";

$trad['playstation'] = "PlayStation - 1995";
$trad['tplaystation'] = "PlayStation is a video game console from Sony, released on December 3, 1994 in Japan and on September 9, 1995. Since launching until 2006 (when its production was extinct ), the PlayStation sold more than 100 million units, only surpassed by its successor, the PlayStation 2. The origin of the PlayStation goes back to 1990, when Nintendo planned a CD accessory for the Super Nintendo. Sony has decided to launch it as an independent video game console, making that announcement in 1993 at the company's headquarters in New York City. Nintendo has tried legal action to prevent launching and manufacturing, but lost in various instances in the United States and Japan. ";

$trad['64'] = "Nitendo 64 - 1996";
$trad['t64'] = "Nintendo 64 (abbreviated as only, N64) is the third home video game console of the Japanese company Nintendo, launched on June 23, 1996 in Japan and on September 29 in the USA. Nintendo 64 had only three titles to launch: Super Mario 64, Wave Race 64 and PilotWings 64. Already when it was released in Europe on March 1, 1997, the console also had the game Star Wars: Shadows of the Empire. It was the last console to use a cartridge (called by Nintendo of Game Pack), distributed in Brazil initially by the company Playtronic and later by Gradiente Eletrônicos.In Portugal, it was distributed by Concentra.The console was announced in 1993 with the codename Project Reality.";
$trad['t642'] = "<br />In 1995 it was first introduced under the name Nintendo Ultra 64, having been renamed Nintendo 64 in February 1996 (5 months before launch). acronym stands for Nintendo Ultra Sixty Four - the project's codename). ";

$trad['dreamcast'] = "Sega Dreamcast - 1999";
$trad['tdreamcast'] = "Sega Dreamcast (Japanese: codenames were Blackbelt, Dural and Katana during its development) was the last video game console of Sega and the successor of Sega Saturn. objective of recovering the console market with a sixth-generation system, was created to technologically beat the Sony PlayStation and Nintendo 64. Although it was considered a console that was ahead of its time (it was released 15 months before the PlayStation 2 and three years before the GameCube and Xbox), it failed to gain enough strength before the launch of PlayStation 2 in March 2000 .. ";

$trad['playstation2'] = "PlayStation 2 - 2000";
$trad['tplaystation2'] = "PlayStation 2 (PS2) is the second console of Sony, after the original PlayStation. Its development was announced in March of 1999 and was released in Japan in March of 2000. The North American version was later released on October 26, 2000. After a slow first year, the PlayStation 2 has grown to become the most popular console in videogames history, with more than 120 million units sold in 2008. Although its successor PlayStation 3 has been released, PS2 continues to be manufactured and new games are produced. ";

$trad['cube'] = "Game Cube - 2001";
$trad['tcube'] = "Nintendo GameCube (aka Cube , abbreviated GCN) is a video game console produced by the Japanese company Nintendo, launched in the US and Japanese markets in November 2001. It is the successor to the Nintendo 64, and his codename during the production was Dolphin.In Nintendo's intention to launch this video game was to try to resume the lost market for Sony and its Playstation.This console brought some new features such as interaction with the Game Boy Advance portable console and a control designed for The Legend of Zelda: The Wind Waker, Super Mario Sunshine, Metroid Prime and Resident Evil 4. Nintendo announced the end of GameCube production at the beginning of 2007. Its model code is DOL-001 (whose acronym comes from DOLphin - the console's codename). ";

$trad['xbox'] = "Microsoft X-Box - 2001";
$trad['txbox'] = "Released in North America on November 15, 2001, Xbox only arrived in Japan on February 22, 2002 and the rest of the world on March 14, 2002. It was the first console sold by an American company in the new century after the Atari's Jaguar discontinued in 96. With 64 MB of RAM and internal space between 8 and 10 GB, the console wanted to snag the Japanese market, which was more in evidence after years of which was dominated by Nintendo and Sega.The X-machine was not as successful in this quest as the European market, but the flagship of Microsoft with its new console was an exclusive shooting game called Halo, which put the player in the Space Chief Master Chief. The game was a success and to this day is compared to great titles of the 90's, like Perfect Dark and GondenEye 007, two games ";
$trad['txbox2'] = "made by developer Rare. Font: <a href=' https://aidobonsai.com/tag/a-completa-historia-dos-video-games/'>Aido Bonsai</a>";

/*pagina plataformas atuais*/

$trad['ps4'] = "Playstation 4";
$trad['tps4'] = "The PlayStation 4 (PS4) is the latest console produced by Sony, after the PlayStation 3 as a console console and after the PlayStation Vita in the general line of consoles of Sony. The launch date for the console was November 15, 2013 in the United States and November 29, 2013 in Latin America (including Brazil) and Europe, according to data released by Sony itself. The price of the console is US $ 399.00 or something around $ 1000.00 in the United States of America, while in Brazil the price reached $ 3,999.00 at launch. Currently the console is already assembled in Brazil having its price reduced to R $ 2600,00 at first. The console introduces the Dualshock 4 controller, which features new features compared to Dualshock 3 and Dualshock 2. Sony unveiled the PS4 Pro (PS4 Pro), the revised and most powerful version of PS4 confirmed by the manufacturer weeks before E3 2013, during a technical demonstration in New York on 7 September.";

$trad['txboxone'] = "Xbox One is a Microsoft-produced video game console, the company's third-largest since the launch of the Xbox, and is marketed eight years after the launch of the Xbox 360. The Xbox One features games with higher-definition graphics than those seen on its predecessor and similar to those presented by its biggest competitor, the PlayStation 4. The Xbox One was announced on May 21, 2013, presented to the public by Microsoft's interactive entertainment business president Don Mattrick at an event called Xbox Reveal, as the successor to the Xbox 360. It competes with the Nintendo Wii U and the PlayStation 4. Its official launch was made in November 2013 costing $ 499.00 (€ 499.00 or R$ 2.299,00).";

$trad['txboxone1'] = "The Xbox One codename for the development of the Xbox One was called Durango and was officially announced on May 21, 2013. After the launch of the game, Microsoft unveiled that it would require the console to have a constant internet connection to work, stating that it would bring a number of benefits including developers who will be able to rely on a connection to Microsoft servers for cloud computing and allowing players to share game titles, players would have to authenticate their game every 24 hours through a constant connection to the internet , including single-player and offline games, and digital rights management restrictions would mean that players would be obliged to exchange their games only in participating stores, whereas disks could only be shared once, and only with one friend who had been on the player's friend list for more than 30 days. ";

$trad['tswitch'] = "Nintendo Switch, called during its development of NX, is a videogame console produced by the Japanese company Nintendo, having been revealed on October 20, 2016. It was officially launched on March 3, 2017, and the launch price is US $ 299.99. At the time of the launch, Sony and Microsoft, the main competitors of Nintendo, used Twitter to celebrate the new console. The switch is a desktop console, but it is a tablet-like hybrid that can be docked with a dock and thus be turned into a console table. The console also has two attachable wireless controllers on each side, called by Nintendo of Joy-Con, that can be used individually or coupled to the main unit (in portable mode) or produced to a gamepad-like base (in the home ";
$trad['tswitch2']= "mode). Although the console is a hybrid and appears to be in the form of a laptop, Nintendo has repeatedly reinforced that the Nintendo Switch is primarily a desktop console and that this will not succeed the Nintendo 3DS. In addition, the Switch is gradually replacing its predecessor, Wii U, including games that were originally released and planned for it, such as Mario Kart 8 and The Legend of Zelda: Breath of the Wild. problems in the initial launch lots such as left-handed Joy-Con sync problems and few titles available on the first day, the Nintendo Switch managed to sell more than 1.5 million in the first week only, having a much better commercial start than the Wii U and even Nintendo 3DS.";

$trad['txboxx'] = "The Xbox One X is for the next Microsoft console. It's slated for release on November 7, 2017. The Xbox One X will be the third console to join the Xbox One family. It is the most powerful console in the world and the smallest Xbox of all time. The Xbox One X looks much like the predecessor of Xbox One S, but now appears in gray space. The USB port on the front of the console now appears on the right side. The Xbox One X is also smaller than the original Xbox One and One S. The eject button is now below the disk drive rather than to the right of it, as in older models. It also appears that the controller has not changed beyond being in gray space.";

$trad['txboxx2']= "The cooling fan was also shifted from the top of the console to the back. During its E3 2017 press conference, Microsoft officially launched the Xbox One X, a high-end version of Xbox One, which will be released in November 2017 First provoked at E3 2016 under the code name, Xbox One X has upgraded hardware that is primarily designed to play games with 4K resolution and supersample to provide graphical enhancements on high definition monitors. Xbox One X will also provide performance gains for existing Xbox One titles; for example, Halo 5: Guardians, which uses a scaling system that dynamically decreases game resolution when needed to maintain a consistent frame rate, was able to perform its native resolution without scaling in Xbox One X.";

$trad['tnu'] = " Wii U is Nintendo's video game console. It was presented at the Electronic Entertainment Expo (E3) on June 7, 2011 as the successor to the Wii. Soon after the announcement there was a 5.7% drop in Nintendo shares, a large drop that had not occurred since the launch of the Wii in 2006. In the online system, a change already revealed perspective is a system of unique accounts of users, abandoning the Wii Friend Codes. The Wii U was released on November 18, 2012 in North America, November 30 in Europe and December 8 in Japan. In Brazil, its official launch was on November 26, 2013, for the value of 1.9 thousand reais Through importers, however, the product was already available.";

$trad['tnu2']= " Its classification in generation is controversial, some affirm that it is of eighth generation, rumors that appeared soon after its launching when it was not known the technical specifications of the console. Soon after, some sources stated, based on the technical specifications of the console that it would fit best in the seventh generation, due to the similarity of computing power between him, Wii U, and Playstation 3 and Xbox 360; and both share the same architecture, PowerPC, unlike the Playstation 4 and Xbox One that use x86_64 architecture. Wii U had mixed press reception, and slow adoption by consumers. Although it was released a year earlier than its competitors, the PlayStation 4 and Xbox One, Wii U's sold less than both (10 million units by October 2015). The review noted some issues with aspects of the console user interface and the high power of Wii U compared to PS4 and Xone and the limited usability of Game Pad with screen in several major titles, a confusing marketing campaign from Nintendo, and the incipient third-party support in comparison to competitors. Several third party known as Electronic Arts and Ubisoft drastically reduced support given to the Wii U in comparison to the PlayStation 4 and Xbox One. The production of Wii U officially ended in January 2017. In March 2017, Nintendo launched a new console Home, the Nintendo Switch";

$trad['t360'] = "Xbox 360 is a gaming console of the seventh generation of video game consoles produced by Microsoft and released on November 22, 2005 in the United States, on December 2, 2005 in Europe and on December 10, 2005 was released in Japan. [ The main features of Xbox 360 are its Xbox Live service that allows gamers to compete online, download arcade games, game demos, trailers, TV shows, music and movies. March 2007 Microsoft announced the launch, on April 29 in the United States, of a third version of the console, the Xbox 360 Elite. On November 4, 2010, officially was released the new version called Xbox 360";

$trad['t3602']= " (popularly known as Xbox 360 Slim) along with the exclusive Kinect motion sensor. Its successor is the Xbox One. The Xbox 360 was featured on the Xbox 360 Revelation show on MTV on May 12, 2005, with details regarding the release and games released a week later at E3. In Brazil, the Xbox 360 has been officially sold by Microsoft since December 1, 2006 making it the first gaming console to be marketed directly by its manufacturer in the country. Previous versions of the console Pro, Premium and Core, accompanied different accessories and configurations have also been withdrawn from the market. Other special packages were distributed by Microsoft, including versions of Call of Duty Modern Warfare 2, Halo 3, Resident Evil 5 and others.";

$trad['tps3'] = "The PlayStation 3 (officially abbreviated as PS3) is the third video game console produced by Sony Computer Entertainment and the successor to the PlayStation 2 as part of the PlayStation series. The PlayStation 3 competes against the Xbox 360 and Nintendo Wii as part of the seventh generation of video game consoles. The main feature that distinguishes PlayStation 3 from its predecessors is its unified online gaming service, the PlayStation Network, which runs counter to policy Sony's official dependence on game developers to achieve such an experience. Other features of the console include its robust multimedia capabilities, its connectivity to PlayStation Portable and PlayStation Vita, and the use of Blu-ray Disc high-definition optical disc format as its primary storage medium. ";

$trad['tps32']= " The PlayStation 3 was also the first Blu-ray player on the market compatible with the 2.0 specification. [15] The PlayStation 3 was released on November 11, 2006 in Japan, November 17, 2006 in North America, March 16, 2007 in the United Kingdom and Republic of Ireland and on March 23, 2007 in most of Europe and Oceania. Two SKUs were released at launch: a basic model with 20 GB hard drive (HDD) and a premium model with a 60 GB hard drive and several additional features (the 20 GB model was not released in Europe or Oceania). Since then, several revisions have been made to the console's available models, particularly with the launch of a new slim model in September 2009, coinciding with the redesign of the console and its logo. In February 2013, Sony announced the launch of its successor , the PlayStation 4, which was released on February 22, 2014 in Japan (November 15, 2013 in North America and the 29th in Europe and Latin America).";
$trad['tfonte'] = "Source:<a href='https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:P%C3%A1gina_principal'>Wikipédia</a>";

/******************* Notícias  ***********************/
$trad['fonte'] = "Source";
$trad['recentes'] = "Recent";
$trad['novidadeSemana'] = "News of the week";
$trad['secoes'] = "Other Sections of the Site";
$trad['texto_erro'] = "No news was found with this URL ...";

$noticias["1"]["id"] = 1;
$noticias["1"]["titulo"] = "You can already play Counter-Strike 1.6 on your Android phone";
$noticias["1"]["imagem"] = "noticias/cs.jpg";
$noticias["1"]["texto"] = "Anyone who is passionate about shooting games surely knows Counter-Strike. Emperor of the lan houses, this game has returned to the top of eSports games and competitions through Counter-Strike: Global Offensive. Now, those who miss the versions Counter-Strike 1.5 or 1.6 can now play them directly on your phone. That's right: You can kill nostalgia with this device that is probably close to you right now. A team of programmers led by Alibek Omarov released a file on Github last Saturday (17) for those interested in downloading and installing the game inside their Android device. The requirements for the execution are a bit demanding: in addition to the Xash3D software, players also need to have the game inside the Steam platform. Of course, because Counter-Strike's gameplay is computer-centric, you may feel a bit of difficulty driving the character and even shooting through the little screen, but some peripherals can help in that process, right?";
$noticias["1"]["fonte"] = "https://www.tecmundo.com.br/windows-10/78746-ele-voltou-classico-jogo-paciencia-windows-10.htm";
$noticias["1"]["data"] = "Date: 2017-11-20";

$noticias["2"]["id"] = 2;
$noticias["2"]["titulo"] = "He returned! The classic game 'Patience' will be in Windows 10";
$noticias["2"]["imagem"] = "noticias/paciencia.jpg";
$noticias["2"]["texto"] = "Microsoft is willing to turn Windows 10 into the \"people's operating system \". The main proof of this is that they revived the Start Menu after several requests - and, according to a recent post on Twitter, brought from limbo one of the classic features of the product.
The program \"Patience \" is back. The card game was caught in a recent build of Windows 10 under the name of \"Microsoft Solitaire Collection Preview\" and seems to be in testing, but should survive until the final version.
The game celebrates 25 years of \"Patience\" (yes, it exists since 1990!) And brings themes, scores, statistics and even challenges. In this version, it does not save data after the program is closed, being only a demonstration version to increase the anxiety of the fans.
If you do not remember, \"Patience \" consists of an individual game whose purpose is to place all cards in ascending order by suit, much of which starts face down. Twitter user @stroughtonsmith was the one who caught the news.";
$noticias["2"]["fonte"] = "https://www.tecmundo.com.br/jogos/103817-voce-jogar-counter-strike-1-6-celular-android.htm";
$noticias["2"]["data"] = "Date: 2017-11-20";

$noticias["3"]["id"] = 3;
$noticias["3"]["titulo"] = "Atari sued Nestlé for announcement of KitKat that imitated Breakout game";
$noticias["3"]["imagem"] = "noticias/kitkat.jpg";
$noticias["3"]["texto"] = "Atari is suing Nestlé for having \"copied\" its famous 1970s breakout game into a TV ad for the chocolate KitKat. The video in question showed a series of actors playing video games on a sofa that suddenly enter into a \"real game\" in which KitKat bars make up the original Breakout blocks.
With this, people begin to be played on the screen to eat the candy as if they were the ball that goes up and down in the Atari game. Breakout was developed by the company in 1976 and was inspired by the Pong game, considered one of the first computer games in the world and the first in history to generate some profit for its creators.
Breakout versions are produced to date, and Atari claims in its lawsuit that Nestlé took advantage of the title tradition to sell sweets. The video in question aired in 2016 on British TV and, according to the advertiser, will not be re-released. Although the case took place in the UK, the Atari case was opened in San Francisco, USA. \"We are aware of the lawsuit in the United States and we will strongly defend these claims,\" ​​a Nestlé spokesman in the European country said.
As the litigation is still starting, there is no information on possible developments. But what do you think? Will Nestlé have to pay a fine for Atari?";
$noticias["3"]["fonte"] = "https://www.tecmundo.com.br/cultura-geek/120994-atari-processa-nestle-anuncio-kitkat-imitava-jogo-breakout.htm";
$noticias["3"]["data"] = "Date: 2017-11-20";

$noticias["4"]["id"] = 4;
$noticias["4"]["titulo"] = "Guitar Hero? Anything! Earn points shaking your head in this 'Metal-Game'";
$noticias["4"]["imagem"] = "noticias/metalhero.jpg";
$noticias["4"]["texto"] = "A Japanese electrocore band called Crossfaith recently launched a new game on their site to promote their newest album, \"Freedom\". To play, you just need to have a webcam on your PC and get your head rocked during the band's songs as if you were in a metal show.
The goal is to do headbanging or head-to-head, and if the game finds you slowed or stopped, it complains, \"Why did you stop?\" \"Keep swinging ...\". If you do not obey in up to 10 seconds, all of your progress in music is lost. Click to play.
If you get to the end, the game shows your result, how many swayed you made, and gives you a kind of prize: an art that could be used on your own electrocore album, if you like it. Be that as it may, you can share those results on social networks if you do not get dizzy or, perhaps, headache after the song ends.";
$noticias["4"]["fonte"] = "https://www.tecmundo.com.br/software/119841-site-banda-japonesa-lanca-jogo-balancar-cabeca-durante-musica.htm";
$noticias["4"]["data"] = "Date: 2017-11-20";

$noticias["5"]["id"] = 5;
$noticias["5"]["titulo"] = "'Sansar', Second Life, of virtual reality, enters into public beta";
$noticias["5"]["imagem"] = "noticias/sansar.jpg";
$noticias["5"]["texto"] = "Linden Lab today announced the release of Sansar's public beta, which can be considered primarily a Second Life or even a Minecraft for virtual reality. The difference is that Linden's game is much more graphically advanced and has a very unique business model for today's market.
Essentially, players can enter the game to \"create their experiences,\" which means basically building things in a way that can be harnessed later. Within this scenario, other more professional players can create any three-dimensional graphic element and place to sell in their personal stores within Sansar. The idea is for less savvy users to use these elements to accelerate the building of their own experiences and thereby generate money within the platform. Currently, however, all users can create up to three \"experience\" spaces for free in the game, but if you want to become a creator, you need to sign a plan. Options range from $ 9.99 to $ 99.99.
While investing a good monthly subscription value, these users will be able to earn more than they spend in-game selling their creations. The developer, of course, gets a share of the transactions. The game also allows players to create avatars and talk in real time with others in this virtual world. There are a number of social elements also to help distract the players on the platform.";
$noticias["5"]["fonte"] = "https://www.tecmundo.com.br/cultura-geek/120178-sansar-second-life-realidade-virtual-entra-beta-publico.htm";
$noticias["5"]["data"] = "Date: 2017-11-20";

$noticias["6"]["id"] = 6;
$noticias["6"]["titulo"] = "The gala evening of CBLoL 2017's competitors is coming";
$noticias["6"]["imagem"] = "noticias/cblol.jpg";
$noticias["6"]["texto"] = "Riot Games announced a list of 10 favorite players to receive the nine most important prizes of the second stage of the tournament. The criteria for this relationship are based on overall performance in the Regular Phase (MVP, featured in the match, KDA and performance index). As the Regular Phase ended last weekend (22nd and 23rd), the competitors selected by Riot were not separated by prize category, as everything can change with the Elimination and Final Phase. The new stage begins on August 19, with the contest between INTZ x Pain, and ends on August 20, with RedCanis x Team oNe. The grand final of the Brazilian League of Legends Championship will be decided on September 2 at the Mineirinho gymnasium in Belo Horizonte, Minas Gerais. Sales started on the 17th of this month and values ​​range between $ 30 and $ 80.";
$noticias["6"]["fonte"] = "https://www.tecmundo.com.br/software/119842-noite-gala-competidores-cblol-2017-chegando.htm";
$noticias["6"]["data"] = "Date: 2017-11-20";

$noticias["7"]["id"] = 7;
$noticias["7"]["titulo"] = "Blizzard releases access to StarCraft II for IA training";
$noticias["7"]["imagem"] = "noticias/blizzard.jpg";
$noticias["7"]["texto"] = "Blizzard had already announced a partnership with DeepMind - an Alphabet company focused on artificial intelligence - in November last year, but only today the two companies have released to the world what they are doing. Now, any artificial intelligence researcher can have access to SatrCraft II to train their software.
The title was chosen primarily because it brings a very complex environment in which the AI ​​software has to take thousands of decisions to complete challenges in the game and also plot a more complex plan to complete the game. So far, only DeepMind has been using the game for this purpose, in order to make its software learn to deal with these situations in the same way as humans: taking multiple small decisions virtually instantaneously and still managing to build a bigger plan in the meantime .
To learn to play, artificial intelligence, is performing various wrong activities until you get it right, and with that, you understand the dynamics of the thing. The reverse process is also used, causing the software to often perform a correct action until an error is made. \"DeepMind's scientific mission is to overcome artificial intelligence barriers by developing systems that can learn to solve complex problems. To do so, we've developed agents and tested their skills in a wide variety of environments, from the DeepMind Lab - made for it - to established games such as Atari and Go, \"DeepMind researchers explained in a posting on the subject.
Blizzard has decided to open StarCraft II so that other artificial intelligence researchers can train their software inside the game at no cost.";
$noticias["7"]["fonte"] = "https://www.tecmundo.com.br/software/120607-blizzard-libera-acesso-starcraft-ii-treinamento-ia.htm";
$noticias["7"]["data"] = "Date: 2017-11-20";

$noticias["8"]["id"] = 8;
$noticias["8"]["titulo"] = "Youtuber mounts PC capable of running games in 16K resolution";
$noticias["8"]["imagem"] = "noticias/youtuber.jpg";
$noticias["8"]["texto"] = "While the gaming world is struggling to make 4K gaming a popular reality, Linus Tech Tips channel people are already experimenting with 16K games. Yes, it's a completely absurd resolution by today's standards, but they actually managed to make the whole thing work (after a few problems).
Just so you have an idea, 16K is the equivalent of 64 times our Full HD 1080p standard. If you already have a 4K TV, think that this Linus setup has 16 times more pixels than yours. Incredible, is not it? To make all this equipment work in sync, channel personnel have used four NVIDIA Quadro P5000 video cards, which are powerful GPUs developed for Pixar-level illustrators, for example, or for professionals dealing with large 3D modeling tools. To unite these boards, they still needed a \"Quadrosync\". Only these cards cost about US $ 10,000, more than R $ 31,000 approximately.
We also used 16 4K IPS Acer Predator XB1 monitors to mount the entire image. With only the part of the displays, disregarding the edges, the \"mega screen\" measured 2.39 x 1.35 meters. The motherboard used was a Rampage V Edition 10 6900K from Asus and 32 GB of RAM from Corsair.
Even with all of that, some games did not run right in 16K, such as Rise of The Tomb Raider, which, with staggering, crashed at 3 or 2 frames per second. More basic titles like Minecraft and Half-Life 2 managed to work without much gagging, with an average of 40 fps.";
$noticias["8"]["fonte"] = "https://www.tecmundo.com.br/produto/120381-youtuber-monta-pc-capaz-rodar-jogos-resolucao-16k.htm";
$noticias["8"]["data"] = "Date: 2017-11-20";

/******************* Notícias  ***********************/

/*Página jogos premiados*/
$trad['treddead'] = 'Red Dead Redemption - 2010';
$trad['reddead'] = 'Red Dead Redemption is an action / adventure game developed by Rockstar Games and by Rockstar San Diego. The game was released in 2010 and is available on Xbox 360, Playstation 3 and PC platforms. The game takes place in the year 1911, in the old West. Its gameplay is presented in third person, within an open world, in which the player can interact with all the elements of the form that he prefers.';

$trad['tskyrim'] = 'The Elder Scrolls Skyrim V - 2011';
$trad['skyrim'] = 'Developed by Bethesda product, The Elder Scrolls V - Skyrim brought with it great gameplay, beautiful graphics, great and epic battles among many other surprises included in the game. Released in 2011 the game charmed its players mainly those who were already fans of the franchise or MMORPG games. The game in the open world with several races, giant monsters and dragons brings with it a gameplay in first person, but gives the player the possibility to play in third person.';

$trad['twalking'] = 'The Walking Dead:The Game - 2012';
$trad['walking'] = 'The Walking Dead: The Game developed by Telltale Games is an adventure game, played in third person, with a variety of cinematic camera angles, in which the player, is the protagonist Lee Everett. The player works with a disorganized group of survivors struggling to stay alive in the midst of a zombie apocalypse.';

$trad['tgta'] = 'Grand Theft Auto V - 2013';
$trad['gta'] = 'The game produced by Rockstar North and published in 2013 by Rockstar Games, brings with it an open world game in third person, which allows the player to own homes, firearms, cars, among many other elements. Gta V has also introduced a new character-swapping feature in the game, which allows the player to control three different characters each with their respective story: Michael de Santa, Trevor Philips and Franklin Clinton, three criminals whose stories connect to each other. that the missions are being completed.';

$trad['tdragon'] = 'Dragon Age Inquisition - 2014';
$trad['dragon'] = 'Dragon Age Inquisition is an action RPG game, being the third and main game of the Dragon Age franchise. The game was released in 2014 for PC, Xbox 360, Playstation 3 and Xbox One.';

$trad['twitcher'] = 'The Witcher 3 Wild Hunt - 2015';
$trad['witcher'] = 'The Witcher 3 is an RPG game, which was released for PC platforms, Xbox One and Playstation 4, the game is in third person with open world and gives the player full freedom. Its protagonist is a wizard, who uses swords and spells in a long journey in the Northern Kingdoms.';

$trad['tover'] = 'Overwatch - 2016';
$trad['over'] = 'Overwatch is a first person shooter in multiplayer mode. In the game is used several heroes with specific abilities in the cooperative way with other players, forming two teams that use the cooperation, strategy and gameplay of the players to reach the victory..';
?>