<?php
$trad['home'] = "Home";
$trad['historia'] = "História dos Games";
$trad['plataformas'] = "Plataformas Atuais";
$trad['jogos'] = "Jogo do Ano";
$trad['mapa'] = "Mapa do Site";

/*pagina historia dos games*/

$trad['magnavox'] = "Magnavox Odssey - 1972";
$trad['tmagnavox'] = "O Magnavox Odssey foi primeiro console de video game para conexão em televisão dentro de casa. Foi criado por Ralph Baer que terminou o protótipo em 1968. Chega aos Estados Unidos em 1972 o primeiro console de videogame, o Odyssey 100, fabricado pela Magnavox, subsidiária da Philips holandesa. Existiam 12 jogos para o console, que podiam ser trocados pelo usuário por um mecanismo mais rudimentar que os cartuchos. Apesar da simplicidade, o equipamento oferecia um rifle opcional, para os jogos de tiro. Curiosidades interessantes sobre o Odyssey 100 são a necessidade de se anotar os pontos dos jogos tinham (e por isso folhas de papel acompanhavam o jogo) e que os usuários tinham de colocar cartões em frente à tela da TV para simular o campo do jogo (em um jogo de tênis por exemplo, colocava-se uma cartão verde para parecer grama).";

$trad['pong'] = "Pong Atari - 1975";
$trad['tpong'] = "Pong o console da Atari chegou em 1975. Criado pelo engenheiro Harold Lee, era um jogo de Ping Pong simples, com duas barras verticais e uma bola (quadrado), sem controle de velocidade ou reflexão. Deu início a uma série de video games com este design de dois botões de controle de movimento. Vendeu 150.000 unidades em um ano, uma marca expressiva para a época. O Pong, jogo para arcade criado por Bushnell na Atari, se torna um fenômeno e várias empresas, como a Ramtek e a Nutting, começam a lançar similares. A Atari estabelece contato com a Namco do Japão.";

$trad['coleco'] = "Coleco Telestar - 1976";
$trad['tcoleco'] = "A série Telstar é uma série de máquinas de Pong lançados pela Coleco. Com esse videogame, a Coleco liderou a primeira geração de videogames. O console fez muito sucesso por causa de seus baixos preços (custava 50 dólares em média) e de um pouco de sorte. A Coleco alcançou o primeiro lugar na venda de consoles da primeira geração graças aos baixos preços e a uma sorte extra. Naquela época havia muitas empresas querendo entrar para o ramo de videogames, o único problema é que haviam poucas fabricantes de chips. A príncipal fabricante da época era a General Instruments, que estava sobrecarregada deserviço, porém, a Coleco se adiantou nos pedidos do seu chip foi a única a receber todo o pedido de uma vez.";
$trad['tcoleco2'] = "Com o sobrecarregamento das empresas que produziam chips, algumas das grandes concorrentes da Coleco chegaram a receber somente 20% da encomenda. Resultado: a Coleco liderou. O console da Telstar abaixo foi lançado em 1976 e tinha apenas 3 jogos com 3 níveis de dificuldade. Com toda simplicidade foi vendido mais de um milhão de unidades no mundo.";

$trad['2600'] = "Atari 2600 - 1977";
$trad['t2600'] = "Atari 2600 foi um video game projetado por Nolan Bushnell e lançado em 1978 nos Estados Unidos e em 1983 no Brasil. Considerado um símbolo cultural dos anos 80, foi um fenômeno de vendas no Brasil entre os anos de 1984 a 1986 e seus jogos permanecem na memória de muitos que viveram a juventude nesta época.";

$trad['telejogo'] = "TeleJogo - 1979/1980";
$trad['ttelejogo'] = "Telejogo foi um aparelho de videogame simples produzido no brasil pela philco. Consistia basicamente de traços que subiam ou desciam para rebater um quadrado (bola), o controle era feito através de um dial (como o sintonizador de rádio). No Brasil ele foi comercializado em 1977 pela Ford e pela Philco. O segundo console além dos 10 jogos dessa versão (Hockey, Tênis, Paredão I, Paredão II, Basquete I, Basquete II, Futebol, Barreira, Tiro Alvo I, Tiro Alvo II),tinha um outro detalhe que se destacava, os joysticks. Com eles não era mais necessário ficar perto do console para poder jogar (bem diferente do 1o modelo) Mas uma vez a Philco / Ford caprichou no acabamento, utilizando madeira clara, dando um toque elegante ao aparelho. Outro ponto interessante do design, é que o Telejogo II (assim como o Telejogo) não é simplesmente uma cópia de algum “Pong” estrangeiro, e sim um projeto totalmente brasileiro, mostrando que os fabricantes nacionais tinham total capacidade de concorrer com os aparelhos importados.";

$trad['intellivision'] = "Intellivision I - 1980";
$trad['tintellivision'] = "Intellivision I foi o primeiro console criado pela Mattel em 1980. Na época do seu lançamento, ele custava US$300. Ao todo, foram lançados 125 jogos para o console entre os anos de 1979 e 1989. O console ficou no mercado mesmo depois do grande “Crash de 1984”, onde o mercado de videogames nos EUA sofreu sua maior queda e todos os videogames perderam valor e credibilidade. A primeira versão esteve disponível até o ano de 1983. Intellivision Keyboard Component – Transformava o Intellivision num computador. O teclado possuía como microprocessador o 6502 da Motorola (8 bits) e funcionava em conjunto com o hardware do console.";
$trad['tintellivision2'] = "Possuía também 16Kb de RAM (expansível até 8 Mb), gravador cassete controlado digitalmente prara gravação/leitura de dados e leitura de áudio, portas de expansão e entrada para impressora. PlayCable – Lançado em 1981, o acessório deixava você jogar via TV a cabo. O assinante baixava o jogo para o console. Assim como o teclado, ele era conectado na entrada do cartucho. Foi descontinuado em 1983. Intellivoice – Lançdo em 1982, este acessório adicionava vozes ao videogame. Possuia um chip sintetizador de voz. Apenas 13 jogos eram compatíveis a ele. Sua fabricação acabou no dia 4 de Agosto de 1983.";

$trad['nes'] = "Nintendo (NES) - 1985";
$trad['tnes'] = "Nintendo Entertainment System, ou simplesmente NES (no Brasil apelidado como Nintendinho), é um videogame lançado pela Nintendo na América do Norte, Europa, Asia, Austrália e Brasil. Originalmente lançado no Japão em 1983 com o nome de Nintendo Family Computer, ou apenas Famicom, o sistema foi redesenhado e recebeu o novo nome para ser lançado no mercado americano em 1985. O NES/Famicom foi o videogame de maior sucesso comercial na sua época, ajudou a indústria de videogames a se recuperar da crise de 1983 e estabeleceu novos padrões que seriam seguidos pela indústria. Também foi o primeiro console a ser produzido por terceiros, o que ajudou a divulgar o sistema em todo o mundo. O NES também foi um dos primeiros consoles a se apoiar em jogos feitos por terceiros (não só pela própria fabricante). Seu código de modelo é NES-001..";
    
$trad['7800'] = "Atari 7800 - 1986";
$trad['t7800'] = "Atari 7800 é um console de videogame lançado pela Atari em junho de 1986. Foi desenvolvido para substituir o Atari 5200, que foi um fracasso de mercado, e restabelecer a supremacia da Atari em relação a Intellivision e Colecovision. O Atari 7800, foi projetado para fazer frente aos recentes rivais do fracassado Atari 5200, O Nintendo Entertainment System(NES) e o Sega Master System. Com um processador trabalhando em uma velocidade superior aos rivais, e com um processador de audio de dois canais separados, o Atari 7800 possuia um desempenho superior em velocidade ao NES e gráficos e sons de qualidade similiar ao Sega Master System. Porém, o que decretou o fracasso do Atari 7800, mesmo sendo superior aos concorrente, foi o baixissímo acervo de jogos, uma vez que a maior parte das Software House de sucesso da época, como: Taito, Namco, Capcom e a própria Activision, responsável pelos maiores sucessos da Atari a época do Atari 2600, já possuíam contrato de exclusividade com a Nintendo.";

$trad['3d0'] = "3DO Interactive Multiplayer - 1993";
$trad['t3d0'] = "3DO Interactive Multiplayer (comumente chamado de 3DO) foi o primeiro videogame doméstico com arquitetura de 32 bits. O 3DO consiste em especificações técnicas criadas pela “3DO Company”, que é uma sociedade entre 7 diferentes empresas. Estas especificações são de propriedade intelectual da “3DO Company” e são a parte principal para quem quiser desenvolver um console compatível com o 3DO Interactive Multiplayer. As empresas fabricantes licenciavam os direitos autorais da 3DO para fabricar um sistema baseado nas especificações da “3DO Company”, e empresas de software, licenciavam o direito de desenvolver softwares (jogos e programas) para os sistemas 3DO.";

$trad['jaguar'] = "Jaguar - 1993";
$trad['tjaguar'] = "Jaguar foi um videogame lançado pela Atari no início dos anos 1990 para competir com os consoles de 16 bits da Sega e da Nintendo. O Jaguar possuía cinco processadores, da familia 68000, quatro para processamento geral e um para som. O projeto original iniciou no final da década de 1980, com o nome de Phanter. Era um sistema poderoso para a época, com processador 16 bits e resolução gráfica melhor que o Super Nintendo. Porém novos videogames 32 bits foram lançados como o Amiga CD-32 e o 3DO, a Atari decidiu melhorar o processamento e lançar um pseudo 64 bits. A midia nova para jogos era o CD, o Jaguar era o único dos novos que ainda usava os já ultrapassados cartuchos. Com pouco apoio de empresas tercerizadas, e um eminente fracasso em vista dos novos consoles Sega Saturn da SEGA e Playstation da Sony, a Atari resolveu lançar um drive externo de CD, rebatizando assim o Jaguar de Jaguar-CD.";
$trad['tjaguar2'] = "Poucos Jaguar-CD e drives para este console foram vendidos. Menos ainda foram os jogos fabricados para o Jaguar-CD. Considerado um fracasso, o Jaguar-CD acabou junto com a falência da Atari em 1996.";    
 
$trad['snk'] = "Snk Neo-Geo CD - 1994";
$trad['tsnk'] = "Devido ao alto preço do Neo-Geo AES, a SNK resolve lançar um modelo mais barato, já que o console de cartucho era extremamente caro, e seus jogos também (um bom jogo custava cerca de $300, o preço de lançamento do Neo-Geo CD), a solução foi usar o CD no lugar do cartucho. Nasceu então o Neo-Geo CD, que não devia nada em potência ao Neo-Geo original, e tinha um som melhorado, devido ao sistema de cd, seus jogos também eram bem mais baratos, devido ao uso do cd, que custava em média 5 vezes menos do que os cartuchos utilizados no Neo-Geo, o console lia também cds de música. A primeira versão lançada foi o Neo-Geo CD de gaveta, que saiu apenas no mercado japonês, hoje em dia é um console bastante difícil de encontrar.";
$trad['tsnk2'] = "Logo depois, foi lançado em todo mundo o modelo de Neo-Geo CD de tampa, aonde o cd era posto na parte de cima do console, esse é o modelo mais comum e fácil de encontrar. Apesar de tudo, o Neo-Geo CD tinha um grave problema, devido ao seu drive de cd de 1X de velocidade, os jogos eram carregados muito lentamente, o que tornava o gameplay uma tarefa de paciência algumas vezes, para tentar solucionar isso, a SNK lançou o NeoGeo CDZ que carregava os jogos mais rapidamente (há quem diga que o drive de cd era de 2x, e há quem diga que o drive de cd era o mesmo porém o console dispunha de mais memória, o que carregava os jogos mais rápido), porém, nessa época, o Neo-Geo já estava em declínio, devido ao alto preço das versões de cartucho, e a lentidão da versão cd, o que tornou o Neo-Geo um fracasso comercial, no entanto, sua lista de jogos era ótima, com conversões perfeitas do arcade. O Neo-Geo possui um grande número de fãs até hoje.";

$trad['saturn'] = "Sega Saturn - 1995";
$trad['tsaturn'] = "Sega Saturn é um videogame de 32 bits lançado pela Sega em 1994, no Japão e 1995 nos EUA (e Brasil por meio da Tec Toy). O desenvolvimento do Sega Saturn foi composto de muita especulação, já que não era costume das empresas divulgarem muitas informações concretas durante o desenvolvimento de seus produtos. Em meados de 1991 apareceram diversas notícias sobre um novo console em desenvolvimento pela Sega chamado GigaDrive, que seria baseado na nova placa System 32 que começava a ser utilizada nos fliperamas da época. Do mesmo modo que o Mega Drive foi originado da placa System 16, fazia sentido acreditar que o GigaDrive estivesse sendo desenvolvido utilizando a System 32 como base. Mas o tempo passou e nunca ocorreu uma confirmação oficial sobre o GigaDrive vindo da Sega.";

$trad['playstation'] = "PlayStation - 1995";
$trad['tplaystation'] = "PlayStation é um console video game da Sony, lançado em 3 de dezembro de 1994 no Japão e em 9 de setembro de 1995 nos Estados Unidos. Desde o seu lançamento até 2006 (quando sua produção fora extinta), o PlayStation vendeu mais de 100 milhões de unidades, apenas superado pelo seu sucessor, o PlayStation 2. A origem da PlayStation remonta a 1990, quando a Nintendo planejava um acessório de CD para o Super Nintendo. A Sony fora accionada para fabricar o acessório, mas vários desentendimentos entre as duas empresas fizeram a Nintendo optar por trocar a Sony pela Philips. O aparelho já se encontrava em avançado desenvolvimento e a Sony decidiu lançá-lo no mercado como uma consola de videojogos independente, fazendo esse anúncio em 1993 na feira E3. A Nintendo tentou medidas judiciais para impedir o lançamento e a fabricação, mas perdeu em várias instâncias nos Estados Unidos e Japão.";

$trad['64'] = "Nitendo 64 - 1996";
$trad['t64'] = "Nintendo 64 (abreviada como apenas, N64) é o terceiro console de video-game doméstico da empresa japonesa Nintendo. Lançado em 23 de Junho de 1996 no Japão e em 29 de Setembro nos EUA, o Nintendo 64 contava com apenas três títulos de lançamento: Super Mario 64 , Wave Race 64 e PilotWings 64. Já quando foi lançado na Europa, em 1 de Março de 1997, o console contava também com o jogo Star Wars: Shadows of the Empire. Foi o último console doméstico a utilizar cartucho (chamado pela Nintendo de “Game Pack”), distribuídos no Brasil inicialmente pela empresa Playtronic e posteriormente pela Gradiente Eletrônicos. Em Portugal, foi distribuída pela Concentra. O console foi anunciado em 1993 com o codename “Project Reality”.";
$trad['t642'] = "Em 1995 fora primeiro apresentado com o nome Nintendo Ultra 64, tendo o nome reduzido para Nintendo 64 em Fevereiro de 1996 (5 meses antes do lançamento). Seu código de modelo é NUS-001 (cuja sigla significa Nintendo Ultra Sixty Four – o codinome do projeto).";

$trad['dreamcast'] = "Sega Dreamcast - 1999";
$trad['tdreamcast'] = "Sega Dreamcast (Japonês: os codinomes foram “Blackbelt”, “Dural” e “Katana” durante o seu desenvolvimento) foi o último console de videogames da Sega e o sucessor do Sega Saturn. Com o objetivo de recuperar o mercado dos consoles com um sistema de sexta geração, foi criada por forma a bater tecnologicamente o PlayStation da Sony e a Nintendo 64. Mesmo tendo sido considerada um console que se encontrava “bastante à frente do seu tempo” (foi lançado 15 meses antes do PlayStation 2 e três anos antes do GameCube e do Xbox), ela falhou em ganhar “força” suficiente antes do lançamento do PlayStation 2 em Março de 2000..";

$trad['playstation2'] = "PlayStation 2 - 2000";
$trad['tplaystation2'] = "PlayStation 2 (PS2) é o segundo console da Sony, após o PlayStation original. Seu desenvolvimento foi anunciado em Março de 1999 e foi lançado no Japão em Março de 2000. A versão norte-americana foi mais tarde lançada em 26 de Outubro de 2000. Após um lento primeiro ano, o PlayStation 2 cresceu a ponto de tornar-se o mais popular console da história dos videogames, com mais de 120 milhões de unidades vendidas em 2008. Embora seu sucessor PlayStation 3 tenha sido lançado, PS2 continua sendo fabricado e novos jogos são produzidos.";

$trad['cube'] = "Game Cube - 2001";
$trad['tcube'] = "Nintendo GameCube (apelidado “Cube”, abreviado GCN) é um console de video game produzido pela empresa japonesa Nintendo, lançado no mercado americano e japonês em novembro de 2001. É o sucessor do Nintendo 64, e seu codinome durante a produção era Dolphin. A intenção da Nintendo ao lançar este videogame era tentar retomar o mercado perdido para a Sony e seu Playstation. Este console trouxe algumas novidades como a interação com o console portátil Game Boy Advance e um controle desenhado para melhor se adaptar aos jogadores de todas as idades. Alguns jogos de sucesso para esta plataforma são The Legend of Zelda: The Wind Waker, Super Mario Sunshine, Metroid Prime e Resident Evil 4. A Nintendo anunciou o fim da produção do GameCube no início de 2007. Seu código de modelo é DOL-001 (cuja sigla vem de DOLphin – o codinome do console).";

$trad['xbox'] = "Microsoft X-Box - 2001";
$trad['txbox'] = "Lançado na América do Norte no dia 15 de novembro de 2001, o Xbox só chegou no Japão em 22 de fevereiro de 2002 e no resto do mundo em 14 de março de 2002. Foi o primeiro console vendido por uma empresa americana no novo século, após a descontinuação do Jaguar da Atari, em 96. Com 64 MB de RAM e espaço interno entre 8 e 10 GB, o console queria abocanhar o mercado japonês, que estava mais em evidência após anos de domínio da Nintendo e da Sega. A máquina X não foi tão bem sucedida nessa missão, conquistando mais o mercado europeu. O carro-chefe da Microsoft com seu novo console era um jogo exclusivo de tiro chamado Halo, que colocava o jogador na pele do herói espacial Master Chief. O game foi um sucesso e até hoje é comparado com grandes títulos dos anos 90, como Perfect Dark e GondenEye 007, dois jogos ";
$trad['txbox2'] ="feitos pela desenvolvedora Rare. Fonte: <a href='https://aidobonsai.com/tag/a-completa-historia-dos-video-games/'>Aido Bonsai</a>";

/*pagina plataformas atuais*/

$trad['ps4']= "Playstation 4";
$trad['tps4']= "O PlayStation 4 (PS4) é o mais recente console produzido pela Sony, após o PlayStation 3 como console de mesa e após o PlayStation Vita na linha geral de consoles da Sony. O dia do lançamento do console foi 15 de novembro de 2013 nos Estados Unidos e em 29 de novembro de 2013 na América Latina (incluindo Brasil) e na Europa, de acordo com os dados divulgados pela própria Sony.O preço do console é de US$399.00 ou algo em torno de R$1000,00 nos Estados Unidos da América, enquanto no Brasil o preço atingiu R$3.999,00 no lançamento. Atualmente o console já é montado no Brasil tendo seu preço reduzido para R$2600,00 em um primeiro momento. O console introduz o controle Dualshock 4, que apresenta novas funções em relação ao Dualshock 3 e Dualshock 2. A Sony revelou o Playstation 4 Pro (PS4 Pro), versão revisada e mais potente do PS4 confirmada pela fabricante semanas antes da E3 2013, durante uma demonstração técnica em Nova York, em 7 de Setembro.";

$trad['txboxone'] = "Xbox One é um console de videogame produzido pela Microsoft, o terceiro da empresa desde o lançamento do Xbox, e é introduzido no mercado oito anos após o lançamento do Xbox 360. O Xbox One apresenta jogos com gráficos de alta definição superiores aos vistos no seu antecessor e similares aos apresentados pelo seu maior concorrente, o PlayStation 4. O Xbox One foi anunciado no dia 21 de maio de 2013, apresentado ao público pelo presidente de negócios de entretenimento interativo da Microsoft, Don Mattrick, em um evento chamado Xbox Reveal, como o sucessor do Xbox 360. Ele compete com o Nintendo Wii U e o PlayStation 4. Seu lançamento oficial foi feito em novembro de 2013 custando US$ 499,00 (€ 499,00 ou";
$trad['txboxone1'] = "R$ 2.299,00).  Desde seu lançamento até janeiro de 2016 já foram vendidas mais de 25 milhões de unidades. O codinome de desenvolvimento do Xbox One foi denominado de Durango e foi anunciado oficialmente no dia 21 de maio de 2013. Após o lançamento do console, a Microsoft revelou que seria necessário que o console tivesse uma conexão com a internet constante para funcionar, afirmando que traria uma série de benefícios, incluindo desenvolvedores que serão capazes de confiar em uma conexão com servidores da Microsoft para computação em nuvem e permitindo a partilha de títulos de jogos. Jogadores teriam que autenticar o seu jogo a cada 24 horas através de uma conexão constante com a internet, incluindo single-player e jogos offline. Além disso, as restrições de gerenciamento de direitos digitais significaria que os jogadores seriam obrigados a trocar seus jogos apenas nas lojas participantes, enquanto que os discos só podem ser compartilhados uma vez, e apenas com um amigo que tinha estado na lista amiga do jogador por mais de 30 dias.";

$trad['tswitch'] = "Nintendo Switch , chamado durante seu desenvolvimento de NX, é um console de videogame produzido pela empresa japonesa Nintendo, tendo sido revelado em 20 de outubro de 2016. Foi lançado oficialmente no dia 3 de março de 2017, e o preço de lançamento é de US$299,99. Na ocasião do lançamento, a Sony e a Microsoft, principais concorrentes da Nintendo, usaram o Twitter para comemorar o novo console.O Switch se trata de um console de mesa, mas é um híbrido semelhante a um tablet, o qual pode ser acoplado a um dock e, assim, ser transformado em um console de mesa. O console também conta com dois controles sem fio acopláveis de cada lado, chamados pela Nintendo de Joy-Con, que podem ser usados individualmente ou ser acoplados à unidade principal (no modo portátil) ou ";
$trad['tswitch2']= "a uma base semelhante a um gamepad (no modo caseiro). Apesar do console ser um híbrido e aparentar ter a forma de um portátil, a Nintendo reforçou várias vezes que o Nintendo Switch é primeiramente um console de mesa e que este não irá suceder o Nintendo 3DS. Além disso, aos poucos o Switch está substituindo totalmente o seu antecessor, o Wii U, inclusive tendo jogos que foram originalmente lançados e planejados para o mesmo, tais como Mario Kart 8 e The Legend of Zelda: Breath of the Wild.Mesmo com alguns problemas nos lotes iniciais de lançamento como problemas de sincronização do Joy-Con esquerdo e poucos títulos disponíveis no primeiro dia, o Nintendo Switch conseguiu vender mais de 1,5 milhão apenas na primeira semana, tendo um inicio comercial muito melhor que o do Wii U e até mesmo do Nintendo 3DS.";

$trad['txboxx'] = "O Xbox One X é para o próximo console da Microsoft . Está programado para lançamento em 7 de novembro de 2017. O Xbox One X será o terceiro console para se juntar à família Xbox One . É o console mais poderoso do mundo e o menor Xbox de todos os tempos.O Xbox One X parece muito parecido com o antecessor do Xbox One S , mas agora aparece no espaço cinza. A porta USB na frente do console agora aparece no lado direito. O Xbox One X também é menor do que o original do Xbox One e One S. O botão para ejetar discos está agora abaixo da unidade de disco em vez de estar à direita disso, como em modelos mais antigos. Parece também que o controlador não mudou para além de estar no espaço cinza.";
$trad['txboxx2']= "O ventilador de refrigeração também foi deslocado do topo da consola para a parte de trás.Durante sua conferência de imprensa E3 2017, a Microsoft lançou oficialmente o Xbox One X , uma versão high-end do Xbox One, que será lançado em novembro de 2017. Primeiro provocado na E3 2016 sob o nome de código, o Xbox One X possui hardware atualizado que é projetado principalmente para jogar jogos com resolução de 4K e supersample para fornecer melhorias gráficas em monitores de alta definição. O Xbox One X também fornecerá ganhos de desempenho para os títulos existentes do Xbox One; por exemplo, Halo 5: Guardians , que usa um sistema de escala que diminui dinamicamente a resolução do jogo quando necessário para manter uma taxa de quadros consistente, foi capaz de executar a sua resolução nativa sem dimensionamento no Xbox One X.";

$trad['tnu'] = "Wii U é um console de videogame da Nintendo. Foi apresentado na Electronic Entertainment Expo (E3) em 7 de junho de 2011 como o sucessor do Wii. Logo após o anúncio houve uma queda de 5,7% nas ações da Nintendo,uma grande baixa que não ocorria desde o lançamento do Wii em 2006. No sistema on-line, uma mudança perspectiva já revelada é sistema de contas únicas dos usuários, abandonando os Friend Codes do Wii. O Wii U foi lançado em 18 de Novembro de 2012 na América do Norte, 30 de Novembro na Europa e em 8 de Dezembro no Japão. No Brasil, seu lançamento oficial foi no dia 26 de novembro de 2013, pelo valor de 1,9 mil reais. Através de importadores, no entanto, o produto já estava disponível.";
$trad['tnu2']= " Sua classificação em geração é controversa, alguns afirmam que é de oitava geração, rumores esses que apareceram logo depois do seu lançamento quando não se conhecia as especificações técnicas do console;. Logo depois algumas fontes afirmaram, com base nas especificações técnicas do console que ele se enquadraria de melhor forma na sétima geração, devido a similaridade de poder computacional entre ele, Wii U, e o Playstation 3 e Xbox 360; além de ambos compartilharem da mesma arquitetura, PowerPC, ao contrario do Playstation 4 e Xbox One que usam arquitetura x86_64.O Wii U teve recepção mista da imprensa, e lenta adoção pelos consumidores. Apesar de ter sido lançado um ano antes que seus competidores, o PlayStation 4 e Xbox One, o Wii U's vendeu menos que ambos (10 milhões de unidades até outubro de 2015). A crítica notou alguns problemas com aspectos da interface de usuário do console e a alta potência do Wii U comparado com PS4 e Xone e a limitada usabilidade do Game Pad com tela em vários grandes títulos, uma campanha de marketing confusa da Nintendo, e o incipiente apoio das third-party em comparação aos competidores. Várias third-party conhecidas como Electronic Arts e Ubisoft diminuíram drasticamente o suporte dado ao Wii U em comparação ao PlayStation 4 e Xbox One. A produção do Wii U terminou oficialmente em janeiro de 2017. Em março de 2017, a Nintendo lançou um novo console caseiro, o Nintendo Switch.";

$trad['t360'] = "Xbox 360 é um console de jogos da sétima geração de consoles de videogames produzido pela Microsoft e lançado em 22 de Novembro de 2005 nos Estados Unidos, em 2 de Dezembro de 2005 na Europa e em 10 de Dezembro de 2005 foi lançado no Japão.[carece de fontes]As características principais do Xbox 360 são o seu serviço Xbox Live que permite aos jogadores competir online, baixar jogos arcade, demos de jogos, trailers, shows de TV, música e filmes.[carece de fontes]No dia 28 de Março de 2007 a Microsoft anunciou o lançamento, dia 29 de Abril nos Estados Unidos, de uma terceira versão do console, o Xbox 360 Elite. No dia 4 de novembro de 2010, oficialmente foi lançado a nova versão chamada de Xbox 360  ";
$trad['t3602']= " (popularmente conhecida como Xbox 360 Slim) juntamente com o exclusivo sensor de movimentos Kinect. Seu sucessor é o Xbox One.O Xbox 360 foi apresentado no programa também chamado de Xbox 360 Revelation na MTV em 12 de Maio de 2005, com detalhes a respeito do lançamento e jogos divulgados uma semana depois na E3. No Brasil, o Xbox 360 é vendido oficialmente pela Microsoft desde 1 de dezembro de 2006 tornando-o o primeiro console de jogos a ser comercializado diretamente por seu fabricante no país.Versões anteriores do console Pro, Premium e Core, acompanhavam diferentes acessórios e configurações também foram retiradas de mercado. Outros pacotes especiais foram distribuídos pela Microsoft, incluindo versões do jogo Call of Duty Modern Warfare 2, Halo 3, Resident Evil 5 e outros.";

$trad['tps3'] = "O PlayStation 3 (oficialmente abreviado como PS3) é o terceiro console de videogame produzido pela Sony Computer Entertainment e o sucessor do PlayStation 2 como parte da série PlayStation. O PlayStation 3 compete contra o Xbox 360 e o Nintendo Wii como parte da sétima geração de consoles de videogame.O principal recurso que distingue o PlayStation 3 de seus predecessores é o seu serviço unificado de jogo online, a PlayStation Network, que contraria a política oficial da Sony de depender dos desenvolvedores de jogos para conseguir tal experiência. Outros recursos do console incluem suas robustas capacidades multimídia, sua conectividade com o PlayStation Portable e com o PlayStation Vita e a utilização de formato de disco óptico de alta-definição Blu-ray Disc como seu meio de armazenamento primário.  ";
$trad['tps32']= " O PlayStation 3 também foi o primeiro reprodutor de Blu-ray no mercado compatível com a especificação 2.0.[15]O PlayStation 3 foi lançado em 11de novembro de 2006 no Japão, 17 de novembro de 2006 na América do Norte, 16 de março de 2007 no Reino Unido e República da Irlanda e em 23 de março de 2007 na maior parte da Europa e na Oceania. Foram disponibilizadas duas SKUs ao lançamento: um modelo básico com disco rígido (HDD) de 20 GB e um modelo premium com um disco rígido de 60 GB e vários recursos adicionais (o modelo de 20 GB não foi lançado na Europa ou Oceania). Desde então, várias revisões foram realizadas aos modelos disponíveis do console, particularmente com o lançamento de um novo modelo slim em setembro de 2009, coincidindo com a reformulação do console e seu logotipo.Em fevereiro de 2013, a Sony anunciou o lançamento do seu sucessor, o PlayStation 4, que foi lançado no dia 22 de fevereiro de 2014 no Japão (15 de novembro de 2013 na América do Norte e 29 do mesmo mês na Europa e América Latina).";
$trad['tfonte'] = "Fonte:<a href='https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:P%C3%A1gina_principal'>Wikipédia</a>";


/******************* Notícias  ***********************/
$trad['fonte'] = "Fonte";
$trad['recentes'] = "Recentes";
$trad['novidadeSemana'] = "Novidades da Semana";
$trad['secoes'] = "Outras Seções do Site";
$trad['texto_erro'] = "Não foi encontrada nenhuma notícia com esta URL...";

$noticias["1"]["id"] = 1;
$noticias["1"]["titulo"] = "Você já pode jogar Counter-Strike 1.6 no seu celular Android";
$noticias["1"]["imagem"] = "noticias/cs.jpg";
$noticias["1"]["texto"] = "Quem é apaixonado por games de tiro com certeza conhece Counter-Strike. Imperador das lan houses, este jogo voltou ao topo dos games e das competições de eSports por meio de Counter-Strike: Global Offensive. Agora, quem sente saudades das versões Counter-Strike 1.5 ou 1.6 já pode jogá-las diretamente no seu celular. Isso mesmo: você pode matar a nostalgia com esse aparelho que provavelmente está pertinho de você nesse momento. Um time de programadores liderados por Alibek Omarov divulgou, no último sábado (17), um arquivo no Github para os interessados baixarem e instalarem o jogo dentro do seu dispositivo Android. Os requerimentos para a execução são um pouco exigentes: além do software Xash3D, os jogadores também precisam ter o game dentro da plataforma Steam. Claro que, como a jogabilidade de Counter-Strike é voltada para os computadores, você talvez sinta um pouco de dificuldade para conduzir o personagem e até atirar por meio da telinha, mas alguns periféricos podem ajudar nesse processo, não é mesmo?";
$noticias["1"]["fonte"] = "https://www.tecmundo.com.br/windows-10/78746-ele-voltou-classico-jogo-paciencia-windows-10.htm";
$noticias["1"]["data"] = "Data: 20/11/2017";

$noticias["2"]["id"] = 2;
$noticias["2"]["titulo"] = "Ele voltou! O clássico jogo 'Paciência' estará no Windows 10";
$noticias["2"]["imagem"] = "noticias/paciencia.jpg";
$noticias["2"]["texto"] = "A Microsoft está disposta a transformar o Windows 10 no \"sistema operacional do povo\". A principal prova disso é que eles reviveram o Menu Iniciar após vários pedidos — e, segundo uma postagem recente no Twitter, trouxeram do limbo um dos recursos mais clássicos do produto.
O programa \"Paciência\" está de volta. O jogo de cartas foi flagrado em uma build recente do Windows 10 sob o nome de \"Microsoft Solitaire Collection Preview\" e parece mesmo estar em testes, mas deve sobreviver até a versão final.
O jogo celebra os 25 anos de \"Paciência\" (sim, ela existe desde 1990!) e traz temas, placares, estatísticas e até desafios. Nessa versão, ele não salva dados após o programa ser fechado, sendo somente uma versão demonstrativa para aumentar a ansiedade dos fãs.
Caso você não se lembre, \"Paciência\" consiste em um jogo individual cujo objetivo é colocar todas as cartas em ordem crescente por naipe, sendo que grande parte começa virada para baixo. O usuário do Twitter @stroughtonsmith foi quem flagrou a novidade.";
$noticias["2"]["fonte"] = "https://www.tecmundo.com.br/jogos/103817-voce-jogar-counter-strike-1-6-celular-android.htm";
$noticias["2"]["data"] = "Data: 20/11/2017";

$noticias["3"]["id"] = 3;
$noticias["3"]["titulo"] = "Atari processa Nestlé por anúncio do KitKat que imitava jogo Breakout";
$noticias["3"]["imagem"] = "noticias/kitkat.jpg";
$noticias["3"]["texto"] = "A Atari está processando a Nestlé por ter “copiado” seu famoso jogo dos anos 1970 Breakout em um anúncio para TV do chocolate KitKat. O vídeo em questão mostrava uma série de atores jogando videogame em um sofá que, de repente, entram em um “game real” no qual barras de KitKat fazem as vezes dos blocos originais de Breakout.
Com isso, as pessoas começam a ser jogadas na tela para comerem os doces como se fossem a bola que fica indo para cima e para baixo no game da Atari. Breakout foi desenvolvido pela empresa em 1976 e teve como inspiração o jogo Pong, considerado um dos primeiros jogos para computador do mundo e o primeiro da história a gerar algum lucro para seus criadores.
Versões de Breakout são produzidas até hoje, e a Atari alega em seu processo que a Nestlé se aproveitou da tradição do título para vender doces. O vídeo em questão foi ao ar em 2016 na TV britânica e, segundo a anunciante, não será reexibido. Apesar de o caso ter acontecido no Reino Unido, o processo da Atari foi aberto em San Francisco, nos EUA. “Nós estamos cientes do processo nos Estados Unidos e vamos nos defender fortemente dessas alegações”, disse um porta-voz da Nestlé no país europeu.
Como o litígio ainda está começando, não há informações sobre possíveis desdobramentos. Mas o que você acha? Será que a Nestlé terá que pagar uma boa multa para a Atari?";
$noticias["3"]["fonte"] = "https://www.tecmundo.com.br/cultura-geek/120994-atari-processa-nestle-anuncio-kitkat-imitava-jogo-breakout.htm";
$noticias["3"]["data"] = "Data: 20/11/2017";

$noticias["4"]["id"] = 4;
$noticias["4"]["titulo"] = "Guitar Hero? Nada! Ganhe pontos chacoalhando a cabeça neste 'Metal-Game'";
$noticias["4"]["imagem"] = "noticias/metalhero.jpg";
$noticias["4"]["texto"] = "Uma banda japonesa de eletrocore chamada Crossfaith lançou recentemente em seu site um novo jogo para promover o seu mais novo álbum, “Freedom”. Para jogar, você só precisa ter uma webcam no seu PC e ficar balançado a cabeça durante as músicas da banda como se estive em um show de metal.
O objetivo é ficar fazendo o headbanging ou bate-cabeça até o fim da faixa e, se o game perceber que você diminuiu o ritmo ou parou, ele reclama: “por que você parou?” “Continue balançando…”. Se você não obedecer em até 10 segundos, todo o seu progresso na música é perdido. Clique para jogar.
Caso você chegue até o final, o game mostra seu resultado, de quantas balançadas você fez, e lhe dá uma espécie de prêmio: uma arte que poderia ser usada em seu próprio álbum de eletrocore, se é que você curte isso. Seja como for, é possível compartilhar esses resultados nas redes sociais se você não ficar tonto ou, quem sabe, com dor de cabeça depois do fim da música.";
$noticias["4"]["fonte"] = "https://www.tecmundo.com.br/software/119841-site-banda-japonesa-lanca-jogo-balancar-cabeca-durante-musica.htm";
$noticias["4"]["data"] = "Data: 20/11/2017";

$noticias["5"]["id"] = 5;
$noticias["5"]["titulo"] = "'Sansar', o Second Life, da realidade virtual, entra em beta público";
$noticias["5"]["imagem"] = "noticias/sansar.jpg";
$noticias["5"]["texto"] = "A Linden Lab anunciou hoje a liberação do beta público de Sansar, que pode ser considerado basicamente um Second Life ou até um Minecraft para realidade virtual. A diferença é que o game da Linden é muito mais avançado graficamente e tem um modelo de negócios bastante único para mercado atual.
Essencialmente, os jogadores podem entrar no game para “criar suas experiências”, o que significa basicamente construir coisas de uma forma que possam ser aproveitadas posteriormente. Dentro desse cenário, outros jogadores mais profissionais podem criar qualquer elemento gráfico tridimensional e colocar para vender em suas lojas pessoais dentro do Sansar. A ideia é que os usuários menos experientes usem esses elementos para acelerar a construção de suas próprias experiências e, com isso, gerem dinheiro dentro da plataforma. Atualmente, entretanto, todos os usuários podem criar até três espaços para “experiências” gratuitamente no game, mas, caso você queira se tornar um criador, é preciso assinar um plano. As opções vão de US$ 9,99 até US$ 99,99.
Apesar de investir um bom valor de assinatura mensal, esses usuários poderão ganhar mais do que gastam dentro do jogo vendendo suas criações. A desenvolvedora, naturalmente, fica com uma parcela das transações. O game ainda permite que os jogadores criem avatares e conversem em tempo real com outras pessoas nesse mundo virtual. Há uma série de elementos sociais também para ajudar a distrair os jogadores na plataforma.";
$noticias["5"]["fonte"] = "https://www.tecmundo.com.br/cultura-geek/120178-sansar-second-life-realidade-virtual-entra-beta-publico.htm";
$noticias["5"]["data"] = "Data: 20/11/2017";

$noticias["6"]["id"] = 6;
$noticias["6"]["titulo"] = "A noite de gala dos competidores do CBLoL 2017 está chegando";
$noticias["6"]["imagem"] = "noticias/cblol.jpg";
$noticias["6"]["texto"] = "A Riot Games anunciou nesta terça-feira (25) uma lista com 10 jogadores favoritos a receber os nove prêmios mais importantes da segunda etapa do torneio. Os critérios dessa relação são baseados no desempenho geral na Fase Regular (MVP, destaque na partida, KDA e índice de performance). Como a Fase Regular acabou no último final de semana (22 e 23), os competidores selecionados pela Riot não foram separados por categoria de premiação, visto que tudo pode mudar com a Fase Eliminatória e a Final. A nova etapa começa no dia 19 de agosto, com a disputa entre INTZ x Pain, e termina no dia 20 de agosto, com RedCanis x Team oNe. A grande final do Campeonato Brasileiro de League of Legends será decidida no dia 2 de setembro, no ginásio do Mineirinho, em Belo Horizonte, Minas Gerais. As vendas iniciaram no dia 17 deste mês e os valores variam entre R$ 30 e R$ 80.";
$noticias["6"]["fonte"] = "https://www.tecmundo.com.br/software/119842-noite-gala-competidores-cblol-2017-chegando.htm";
$noticias["6"]["data"] = "Data: 20/11/2017";

$noticias["7"]["id"] = 7;
$noticias["7"]["titulo"] = "Blizzard libera acesso a StarCraft II para treinamento de IA";
$noticias["7"]["imagem"] = "noticias/blizzard.jpg";
$noticias["7"]["texto"] = "A Blizzard já tinha anunciado uma parceria com a DeepMind — uma empresa da Alphabet focada em inteligência artificial — em novembro do ano passado, mas só hoje as duas companhias liberaram para o mundo o que estão fazendo. Agora, qualquer pesquisador de inteligência artificial pode ter acesso a SatrCraft II para treinar seus softwares.
O título foi escolhido basicamente porque traz um ambiente muito complexo no qual o software de IA tem que tomar milhares de decisões para completar desafios no jogo e também tramar um plano mais complexo para completar o game. Até agora, apenas a DeepMind vinha utilizando o game para esse fim, com o intuito de fazer seu software aprender a lidar com essas situações da mesma forma que humanos: tomando múltiplas pequenas decisões de forma praticamente instantânea e ainda conseguindo montar um plano maior enquanto isso.
Para aprender a jogar, a inteligência artificial, vai realizando diversas atividades erradas até conseguir acertar e, com isso, vai entendendo a dinâmica da coisa. O processo inverso também é utilizado, fazendo o software realizar muitas vezes uma ação correta até que um erro seja cometido. “A missão científica da DeepMind é superar barreiras da inteligência artificial desenvolvendo sistemas que podem aprender a resolver problemas complexos. Para isso, nós desenvolvemos agentes e testamos as habilidades deles em uma grande diversidade de ambientes, desde o DeepMind Lab — feito para isso — até games estabelecidos, como Atari e Go”, explicaram os pesquisadores da DeepMind em uma postagem sobre o assunto.
A Blizzard resolveu abrir StarCraft II para que outros pesquisadores de inteligência artificial possam treinar seus softwares dentro do game sem custo.";
$noticias["7"]["fonte"] = "https://www.tecmundo.com.br/software/120607-blizzard-libera-acesso-starcraft-ii-treinamento-ia.htm";
$noticias["7"]["data"] = "Data: 20/11/2017";

$noticias["8"]["id"] = 8;
$noticias["8"]["titulo"] = "Youtuber monta PC capaz de rodar jogos em resolução 16K";
$noticias["8"]["imagem"] = "noticias/youtuber.jpg";
$noticias["8"]["texto"] = "Enquanto o mundo dos games está lutando para tonar a jogatina 4K uma realidade popular, o pessoal do canal Linus Tech Tips já está experimentando com jogos em 16K. Sim, é uma resolução completamente absurda para os padrões de hoje, mas eles de fato conseguiram fazer a coisa toda funcionar (depois de alguns problemas).
Só para você ter uma ideia, 16K é a o equivalente a 64 vezes o nosso Full HD 1080p padrãozinho. Se você já tem uma TV 4K, pense que esse setup do Linus tem 16 vezes mais pixels que o seu. Incrível, não? Para fazer todo esse equipamento funcionar em sincronia, o pessoal do canal utilizou quatro placas de vídeo NVIDIA Quadro P5000, que são GPUs bem poderosas desenvolvidas para ilustradores do nível da Pixar, por exemplo, ou para profissionais que lidam com grandes ferramentas de modelagem 3D. Para unir essas placas, eles ainda precisaram de uma “Quadrosync”. Só essas placas custam cerca de US 10 mil, mais de R$ 31 mil aproximadamente.
Foram utilizados ainda 16 monitores 4K IPS Acer Predator XB1 para montar toda a imagem. Contanto só a parte dos displays, desconsiderando as bordas, a “mega tela” mediu 2,39 x 1,35 metros. A placa-mãe utilizada foi uma Rampage V Edition 10 6900K da Asus e 32 GB de RAM da Corsair.
Mesmo com tudo isso, alguns jogos não rodaram direito em 16K, tais como Rise of The Tomb Raider, que, com o escalonamento, travou nos 3 ou 2 quadros por segundo. Títulos mais básicos como Minecraft e Half-Life 2 conseguiram funcionar sem muitos engasgos, com uma média de 40 fps. ";
$noticias["8"]["fonte"] = "https://www.tecmundo.com.br/produto/120381-youtuber-monta-pc-capaz-rodar-jogos-resolucao-16k.htm";
$noticias["8"]["data"] = "Data: 20/11/2017";

/******************* Notícias  ***********************/

/*Jogos premiados*/

$trad['treddead'] = 'Red Dead Redemption - 2010';
$trad['reddead'] = 'Red Dead Redemption é um jogo de ação/aventura desenvolvido pela produtora Rockstar Games, e pela Rockstar San Diego. O game foi lançado em 2010, sendo disponibilizado nas plataformas Xbox 360, Playstation 3 e PC. O jogo se passa no ano de 1911, no velho Oeste. Sua jogabilidade é apresentada em terceira pessoa, dentro de um mundo aberto, em que o jogador pode interagir com todos os elementos da forma que preferir.';

$trad['tskyrim'] = 'The Elder Scrolls Skyrim V - 2011';
$trad['skyrim'] = 'Desenvolvido pela produtota Bethesda, The Elder Scrolls V – Skyrim trouxe consigo uma ótima jogabilidade, belos gráficos, grandes e épicas batalhas entre muitas outras surpresas incluídas no game. Lançado em 2011 o jogo encantou seus jogadores principalmente os que já eram fãs da franquia ou de jogos MMORPG. O game em mundo aberto traz consigo diversas raças, monstros gigantes e dragões traz consigo uma jogabilidade em primeira pessoa, porém dá ao jogador a possibilidade de jogar em terceira pessoa.';

$trad['twalking'] = 'The Walking Dead:The Game - 2012';
$trad['walking'] = 'The Walking Dead: The Game desenvolvido pela Telltale Games é um game de aventura, jogado em terceira pessoa, com uma variedade de ângulos de câmera cinematográfica, em que o jogador, é o protagonista Lee Everett. O jogador trabalha com um grupo desorganizado de sobreviventes lutando para se manter vivo no meio de um apocalipse zombie.';

$trad['tgta'] = 'Grand Theft Auto V - 2013';
$trad['gta'] = 'O jogo produzido pela Rockstar North e publicado em 2013 pela Rockstar Games, traz consigo um game mundo aberto em terceira pessoa, que permite o jogador possuir casas, armas de fogo, carros, entre muitos outros elementos. Gta V trouxe também uma nova funcionalidade de troca de personagens no game, que permite ao jogador controlar três diferentes personagens cada um com sua respectiva história, sendo eles Michael de Santa, Trevor Philips e Franklin Clinton, três criminosos cujas histórias se conectam à medida em que as missões vão sendo concluídas.';

$trad['tdragon'] = 'Dragon Age Inquisition - 2014';
$trad['dragon'] = 'Dragon Age Inquisition é um jogo RPG
	de ação, sendo ele o terceiro e principal jogo da franquia Dragon Age. O jogo foi lançado em 2014 para PC, Xbox 360, Playstation 3 e Xbox One';

$trad['twitcher'] = 'The Witcher 3 Wild Hunt - 2015';
$trad['witcher'] = 'The Witcher 3 é um jogo de RPG, que foi lançado para as plataformas PC, Xbox One e Playstation 4, o jogo é em terceira pessoa com mundo aberto e da ao jogador total liberdade. Seu protagonista é um bruxo, que usa espadas e magias em uma longa jornada nos Reinos do Norte.';

$trad['tover'] = 'Overwatch - 2016';
$trad['over'] = 'Overwatch é um jogo de tiro em primeira pessoa no modo multijogador. No jogo é utilizado diversos heróis com habilidades específicas no modo cooperativo com outros players, formando duas equipes que usam da cooperação, estratégia e jogabilidade dos jogadores para chegar a vitória.';
?>